# What is the goal of your workflow

# Goal: Whenever someone changes the python code, the linter will check if the syntax, format or identation is correct or not

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v4

      # This step will install the a Python Linting tool
      - name: Install Linter tool
        run: pip install ruff
        
      # This step will run the linter
      - name: Check files for Linting
        run: ruff check .
      
